export interface Comercial {
    personType: String,
    businessName: String,
    socialReason: String,
    productsBeingSold: String,
    localNumber: String,
    predioNumber: String,
    sector: String,
    floor: String,
    hallNumber: String,
    originOfProducts: String,
    numberLocals: String,
    qualifiedCraftman: Boolean,
    craftmanCalification: String,
    sellerType: String,
}