export interface Form {
    name: String,
    last: String,
    gender: String,
    dob: String,
    conv: String,
    cedula: String,
    telCelular: String,
    emer: String,
    provincia: String,
    canton: String,
    ciudad: String,
    barrio: String,
    callePri: String,
    nomenclatura: String,
    calleSec: String // End of the personal information
    riseruc: String,
    riserucInput?: String,
    nameNeg?: String,
    razonSoc?: String,
    numLocal?: String,
    predio?: String,
    sector?: String,
    planta?: String,
    pasillo?: String,
    procedencia?: String,
    artesano?: String,
    typeArtesano?: String,
    negocioOw?: String, // End of the local information
    sangre?: String,
    peso?: Number,
    alergia?: Boolean,
    alergiaInput?: String,
    medicicamento?: Boolean,
    medicamentoInput?: String,
    enfermedades?: String,
    seguro?: String,
    conadis?: String,
    carnet?: String,
    jubilacion?: String,
    jubilacionInput?: String
}
