export interface Personal {
    firstName: String,
    lastName: String,
    gender: String,
    dateOfBirth: Date,
    idNumber: String,
    phoneNumber: String,
    cellphoneNumber: String,
    emergencyPhone: String,
    province: String,
    canton: String,
    city: String,
    neighborhood: String,
    mainStreet: String,
    nomenclature: String,
    secondaryStreet: String,
}
